/* basix.js

Author: Pasi Talvitie
Date: 26.11.2017

License: General Public License 3.0

*/

/* DO NOT EDIT THIS FILE */

var bxLibrary = function() {
};

bxLibrary.prototype.LoadFile = function(filepath) {
	    var request = new XMLHttpRequest();
    request.open("GET", filepath, false);
    request.send(null);
    var contents = request.response;
    
    if (contents == null || contents == "") {
    	return null;
    } else {
		return contents;
    }
};

bxLibrary.prototype.RenderViews = function() {
	for (var i=0; i<bxConfig.views.length; i++) {
		var bxViewFileName = bxConfig.views[i];
		var bxViewTag = document.getElementById(bxViewFileName);
		try {
			bxViewTag.innerHTML = this.LoadFile('views/'+bxViewFileName);
			/*bxViewTag.innerHTML = bxAddVariableValues(bxViewTag.innerHTML);*/
		} catch (e) {
			bxViewTag.innerHTML = '<p>Error loading content. Please ensure that there is a file named <b>'+bxViewFileName+'</b> in the <b>/views</b> folder and that it contains at least some HTML tags</p>';
		}
	}
};

bxLibrary.prototype.LoadStyles = function() {
	for (var i=0; i<bxConfig.styles.length; i++) {
		var bxStyleFileName = bxConfig.styles[i];
		try {
			bxStyle = document.createElement('bx-style');
			bxStyle.innerHTML = bxStyle.innerHTML + '\n' + this.LoadFile('styles/'+bxStyleFileName);
			document.head.appendChild(bxStyle);
		} catch (e) {
			console.log("Cannot add style:"+bxStyleFileName);
		}
	}
}
